name: auto_tag
on:
  workflow_dispatch:
    
jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display Build Number
        run: |
          echo "Build Number: $GITHUB_RUN_NUMBER"
          echo "Branch Name : $GITHUB_REF"
          run: echo "BRANCH_NAME : $GITHUB_REF_NAME"

      - name: Get tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1 
        with:
            strip_v: true # Optional: Remove 'v' character from version
            default: v0.0.0 # Optional: Default version when tag not found

      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}

     # - name: Get Branch Name
      #  id: branch-name
       # run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Tag and push current repo code
        run: |
          # git remote set-url origin https://{your-personal-token}@github.com/{organization}/{repo-name}.git
          # TAG="Build_${GITHUB_REF_NAME}_$(date +"%d-%b-%Y_%HH_%MM")"
          TAG="$GITHUB_RUN_NUMBER"
          git tag $TAG
          git push origin $TAG
