name: auto_tag
on:
  workflow_dispatch:
    
jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Display Build Number
        run: |
          echo "Build Number: $GITHUB_RUN_NUMBER"
          echo "Branch Name : $GITHUB_REF"
          echo "BRANCH_NAME : $GITHUB_REF_NAME"

    
      - name: Get Tags
        id: tags
        run: |
          git fetch --tags
          echo "Tags fetched" 

          
      - name: Get Latest Tag
        id: latest-tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)

     # - name: Get Branch Name
      #  id: branch-name
       # run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Tag and push current repo code
        run: |
          # git remote set-url origin https://{your-personal-token}@github.com/{organization}/{repo-name}.git
          # TAG="Build_${GITHUB_REF_NAME}_$(date +"%d-%b-%Y_%HH_%MM")"
          TAG="$GITHUB_RUN_NUMBER"
          git tag $TAG
          git push origin $TAG
