name: auto_tag
on:
  workflow_dispatch:
    
jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag and push current repo code
        run: |
          TAG="Build_${GITHUB_REF_NAME}_$(date +"%d-%b-%Y_%HHr")"
          git tag $TAG
          git push origin $TAG
