name: get-tag-version

on:
  workflow_dispatch:
    
jobs:
  describe-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Describe Tags
        run: |
          git fetch --prune --unshallow
          #latest_tag=$(git describe --tags --abbrev=0 HEAD~)
          branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          echo "Branch Name : $branch_name"
          
          # latest_tag=$(git describe --tags --abbrev=0 $(git rev-list --tags --max-count=1 $branch_name))
          # echo "Latest Tag: $latest_tag"
          # BUILD_NUMBER=$(echo "$latest_tag" | cut -d '-' -f 3)

          latest_release_tag=$(git describe --tags --abbrev=0 --match "$branch_name*")
          echo "Latest Tag: $latest_release_tag"
         
          BUILD_NUMBER=$(echo "$latest_release_tag" | cut -d '-' -f 3)          
          echo "Build Number : $BUILD_NUMBER"
          NEW_BUILD_NUMBER=$((BUILD_NUMBER + 1))
          echo "Build Number : $NEW_BUILD_NUMBER"
          






