name: get-tag-version

on:
  workflow_dispatch:
    
jobs:
  describe-tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Describe Tags
        run: |
          git fetch --prune --unshallow
          latest_tag=$(git describe --tags --abbrev=0 HEAD~)
          echo "Latest Tag: $latest_tag"
          BUILD_NUMBER=$(echo "$latest_tag" | cut -d '-' -f 3)
          echo "Build Number : $BUILD_NUMBER"






